sudo: required
dist: trusty
language: cpp
before_install:
  -  if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get -y install build-essential g++ automake autoconf bison flex openjdk-7-jdk; fi
  -  if [ $TRAVIS_OS_NAME == osx ]; then brew update; brew install clang-omp bison; brew link bison --force; export OMP_NUM_THREADS=2;export CXX=clang-omp++; export SOUFFLECPP=/usr/local/bin/cpp-4.8; export CXXFLAGS=-fopenmp; fi
compiler:
- gcc
- clang
os:
- linux
- osx
matrix:
    exclude:
        - os: osx
          compiler: gcc
script: 
- sh ./bootstrap
- ./configure
- make check 
- cat tests/testsuite.dir/*/*.out
- cat tests/testsuite.dir/*/*.err
