sudo: required
dist: trusty
language: cpp
before_install:
    sudo apt-get -y install debhelper devscripts build-essential g++ automake autoconf bison flex openjdk-7-jdk;
compiler:
- gcc
- clang
os:
- linux
script:
- sh ./bootstrap
- ./configure
- make -j2 check
