// Souffle - A Datalog Compiler
// Copyright (c) 2026 The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// This code tests provenance explanations for rules with multiple constraints.

.pragma "provenance" "explain"

.decl node(x: number)

.decl link(x: number, y: number, z: number)
.output link

node(1).
node(2).
node(3).

link(x, y, z) :- node(x), node(y), node(z), x < y, y < z.
