// Souffle - A Datalog Compiler
// Copyright (c) 2019, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test for programmatic tuple insertion via Python SWIG bindings

.type Node <: symbol
.decl edge(src:Node, dst:Node)
.input edge()
.decl path(src:Node, dst:Node)
.output path()

path(X, Y) :- edge(X, Y).
path(X, Y) :- edge(X, Z), path(Z, Y).
