// Souffle - A Datalog Compiler
// Copyright (c) 2023, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

.comp c {


.decl R(x:number)
.output R()
.decl R_debug = debug_delta(R)

.output R_debug()
R(0).

R(x + 1) :-
    R(x),
    recursive_iteration_cnt() < 100.

}
.init C = c