// Souffle - A Datalog Compiler
// Copyright (c) 2016, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

//max_aggregate

.decl edge(x:number, y:number, c:number)
.input edge

.decl path(x:number, y:number, c:number) btree_max
.output path

path(x, y, c) :- edge(x, y, c).
path(x, y, c1+c2) :- path(x, z, c1), edge(z, y, c2).
