#!/bin/bash
#
# souffle-profiler
# Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at:
# - https://opensource.org/licenses/UPL
# - <souffle root>/licenses/SOUFFLE-UPL.txt

HEADER_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
JAR=$HEADER_DIR/souffleprof.jar
if [ ! -f $JAR ]
then
   JAR=$HEADER_DIR/build/libs/souffleprof.jar
fi

if [ -f $JAR ]
then
   java -jar $JAR "$@"
else
   echo "error: souffleprof.jar file is not installed in directory $HEADER_DIR" 1>&2
   exit 1
fi
